package com.bootdo.devicetree.dao;

import com.bootdo.devicetree.domain.DeviceDo;
import com.bootdo.devicetree.domain.DeviceDoExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DeviceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    int insert(DeviceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    int insertSelective(DeviceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    List<DeviceDo> selectByExample(DeviceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    DeviceDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceDo record);
}