package com.bootdo.devicetree.dao;

import com.bootdo.devicetree.domain.GatewayModelDo;
import com.bootdo.devicetree.domain.GatewayModelDoExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface GatewayModelDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_gateway_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_gateway_model
     *
     * @mbg.generated
     */
    int insert(GatewayModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_gateway_model
     *
     * @mbg.generated
     */
    int insertSelective(GatewayModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_gateway_model
     *
     * @mbg.generated
     */
    List<GatewayModelDo> selectByExample(GatewayModelDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_gateway_model
     *
     * @mbg.generated
     */
    GatewayModelDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_gateway_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GatewayModelDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_gateway_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GatewayModelDo record);
}