package com.bootdo.devicetree.dao;

import com.bootdo.devicetree.domain.OrgstationDo;
import com.bootdo.devicetree.domain.OrgstationDoExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface OrgstationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_orgstation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_orgstation
     *
     * @mbg.generated
     */
    int insert(OrgstationDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_orgstation
     *
     * @mbg.generated
     */
    int insertSelective(OrgstationDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_orgstation
     *
     * @mbg.generated
     */
    List<OrgstationDo> selectByExample(OrgstationDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_orgstation
     *
     * @mbg.generated
     */
    OrgstationDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_orgstation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrgstationDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_orgstation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrgstationDo record);
}