package com.bootdo.devicetree.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class DeviceDoExample implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public DeviceDoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDevIsNull() {
            addCriterion("dev is null");
            return (Criteria) this;
        }

        public Criteria andDevIsNotNull() {
            addCriterion("dev is not null");
            return (Criteria) this;
        }

        public Criteria andDevEqualTo(String value) {
            addCriterion("dev =", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevNotEqualTo(String value) {
            addCriterion("dev <>", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevGreaterThan(String value) {
            addCriterion("dev >", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevGreaterThanOrEqualTo(String value) {
            addCriterion("dev >=", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevLessThan(String value) {
            addCriterion("dev <", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevLessThanOrEqualTo(String value) {
            addCriterion("dev <=", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevLike(String value) {
            addCriterion("dev like", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevNotLike(String value) {
            addCriterion("dev not like", value, "dev");
            return (Criteria) this;
        }

        public Criteria andDevIn(List<String> values) {
            addCriterion("dev in", values, "dev");
            return (Criteria) this;
        }

        public Criteria andDevNotIn(List<String> values) {
            addCriterion("dev not in", values, "dev");
            return (Criteria) this;
        }

        public Criteria andDevBetween(String value1, String value2) {
            addCriterion("dev between", value1, value2, "dev");
            return (Criteria) this;
        }

        public Criteria andDevNotBetween(String value1, String value2) {
            addCriterion("dev not between", value1, value2, "dev");
            return (Criteria) this;
        }

        public Criteria andAcqintIsNull() {
            addCriterion("acqInt is null");
            return (Criteria) this;
        }

        public Criteria andAcqintIsNotNull() {
            addCriterion("acqInt is not null");
            return (Criteria) this;
        }

        public Criteria andAcqintEqualTo(Long value) {
            addCriterion("acqInt =", value, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintNotEqualTo(Long value) {
            addCriterion("acqInt <>", value, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintGreaterThan(Long value) {
            addCriterion("acqInt >", value, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintGreaterThanOrEqualTo(Long value) {
            addCriterion("acqInt >=", value, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintLessThan(Long value) {
            addCriterion("acqInt <", value, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintLessThanOrEqualTo(Long value) {
            addCriterion("acqInt <=", value, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintIn(List<Long> values) {
            addCriterion("acqInt in", values, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintNotIn(List<Long> values) {
            addCriterion("acqInt not in", values, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintBetween(Long value1, Long value2) {
            addCriterion("acqInt between", value1, value2, "acqint");
            return (Criteria) this;
        }

        public Criteria andAcqintNotBetween(Long value1, Long value2) {
            addCriterion("acqInt not between", value1, value2, "acqint");
            return (Criteria) this;
        }

        public Criteria andUpmIsNull() {
            addCriterion("upm is null");
            return (Criteria) this;
        }

        public Criteria andUpmIsNotNull() {
            addCriterion("upm is not null");
            return (Criteria) this;
        }

        public Criteria andUpmEqualTo(Long value) {
            addCriterion("upm =", value, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmNotEqualTo(Long value) {
            addCriterion("upm <>", value, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmGreaterThan(Long value) {
            addCriterion("upm >", value, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmGreaterThanOrEqualTo(Long value) {
            addCriterion("upm >=", value, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmLessThan(Long value) {
            addCriterion("upm <", value, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmLessThanOrEqualTo(Long value) {
            addCriterion("upm <=", value, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmIn(List<Long> values) {
            addCriterion("upm in", values, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmNotIn(List<Long> values) {
            addCriterion("upm not in", values, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmBetween(Long value1, Long value2) {
            addCriterion("upm between", value1, value2, "upm");
            return (Criteria) this;
        }

        public Criteria andUpmNotBetween(Long value1, Long value2) {
            addCriterion("upm not between", value1, value2, "upm");
            return (Criteria) this;
        }

        public Criteria andPrototypeIsNull() {
            addCriterion("protoType is null");
            return (Criteria) this;
        }

        public Criteria andPrototypeIsNotNull() {
            addCriterion("protoType is not null");
            return (Criteria) this;
        }

        public Criteria andPrototypeEqualTo(String value) {
            addCriterion("protoType =", value, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeNotEqualTo(String value) {
            addCriterion("protoType <>", value, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeGreaterThan(String value) {
            addCriterion("protoType >", value, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeGreaterThanOrEqualTo(String value) {
            addCriterion("protoType >=", value, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeLessThan(String value) {
            addCriterion("protoType <", value, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeLessThanOrEqualTo(String value) {
            addCriterion("protoType <=", value, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeLike(String value) {
            addCriterion("protoType like", value, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeNotLike(String value) {
            addCriterion("protoType not like", value, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeIn(List<String> values) {
            addCriterion("protoType in", values, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeNotIn(List<String> values) {
            addCriterion("protoType not in", values, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeBetween(String value1, String value2) {
            addCriterion("protoType between", value1, value2, "prototype");
            return (Criteria) this;
        }

        public Criteria andPrototypeNotBetween(String value1, String value2) {
            addCriterion("protoType not between", value1, value2, "prototype");
            return (Criteria) this;
        }

        public Criteria andModeltypeIsNull() {
            addCriterion("modelType is null");
            return (Criteria) this;
        }

        public Criteria andModeltypeIsNotNull() {
            addCriterion("modelType is not null");
            return (Criteria) this;
        }

        public Criteria andModeltypeEqualTo(String value) {
            addCriterion("modelType =", value, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeNotEqualTo(String value) {
            addCriterion("modelType <>", value, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeGreaterThan(String value) {
            addCriterion("modelType >", value, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeGreaterThanOrEqualTo(String value) {
            addCriterion("modelType >=", value, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeLessThan(String value) {
            addCriterion("modelType <", value, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeLessThanOrEqualTo(String value) {
            addCriterion("modelType <=", value, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeLike(String value) {
            addCriterion("modelType like", value, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeNotLike(String value) {
            addCriterion("modelType not like", value, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeIn(List<String> values) {
            addCriterion("modelType in", values, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeNotIn(List<String> values) {
            addCriterion("modelType not in", values, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeBetween(String value1, String value2) {
            addCriterion("modelType between", value1, value2, "modeltype");
            return (Criteria) this;
        }

        public Criteria andModeltypeNotBetween(String value1, String value2) {
            addCriterion("modelType not between", value1, value2, "modeltype");
            return (Criteria) this;
        }

        public Criteria andTimeoutIsNull() {
            addCriterion("timeOut is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutIsNotNull() {
            addCriterion("timeOut is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutEqualTo(Long value) {
            addCriterion("timeOut =", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotEqualTo(Long value) {
            addCriterion("timeOut <>", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutGreaterThan(Long value) {
            addCriterion("timeOut >", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutGreaterThanOrEqualTo(Long value) {
            addCriterion("timeOut >=", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutLessThan(Long value) {
            addCriterion("timeOut <", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutLessThanOrEqualTo(Long value) {
            addCriterion("timeOut <=", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutIn(List<Long> values) {
            addCriterion("timeOut in", values, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotIn(List<Long> values) {
            addCriterion("timeOut not in", values, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutBetween(Long value1, Long value2) {
            addCriterion("timeOut between", value1, value2, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotBetween(Long value1, Long value2) {
            addCriterion("timeOut not between", value1, value2, "timeout");
            return (Criteria) this;
        }

        public Criteria andPorttypeIsNull() {
            addCriterion("portType is null");
            return (Criteria) this;
        }

        public Criteria andPorttypeIsNotNull() {
            addCriterion("portType is not null");
            return (Criteria) this;
        }

        public Criteria andPorttypeEqualTo(String value) {
            addCriterion("portType =", value, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeNotEqualTo(String value) {
            addCriterion("portType <>", value, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeGreaterThan(String value) {
            addCriterion("portType >", value, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeGreaterThanOrEqualTo(String value) {
            addCriterion("portType >=", value, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeLessThan(String value) {
            addCriterion("portType <", value, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeLessThanOrEqualTo(String value) {
            addCriterion("portType <=", value, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeLike(String value) {
            addCriterion("portType like", value, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeNotLike(String value) {
            addCriterion("portType not like", value, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeIn(List<String> values) {
            addCriterion("portType in", values, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeNotIn(List<String> values) {
            addCriterion("portType not in", values, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeBetween(String value1, String value2) {
            addCriterion("portType between", value1, value2, "porttype");
            return (Criteria) this;
        }

        public Criteria andPorttypeNotBetween(String value1, String value2) {
            addCriterion("portType not between", value1, value2, "porttype");
            return (Criteria) this;
        }

        public Criteria andSerialidIsNull() {
            addCriterion("serialID is null");
            return (Criteria) this;
        }

        public Criteria andSerialidIsNotNull() {
            addCriterion("serialID is not null");
            return (Criteria) this;
        }

        public Criteria andSerialidEqualTo(String value) {
            addCriterion("serialID =", value, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidNotEqualTo(String value) {
            addCriterion("serialID <>", value, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidGreaterThan(String value) {
            addCriterion("serialID >", value, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidGreaterThanOrEqualTo(String value) {
            addCriterion("serialID >=", value, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidLessThan(String value) {
            addCriterion("serialID <", value, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidLessThanOrEqualTo(String value) {
            addCriterion("serialID <=", value, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidLike(String value) {
            addCriterion("serialID like", value, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidNotLike(String value) {
            addCriterion("serialID not like", value, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidIn(List<String> values) {
            addCriterion("serialID in", values, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidNotIn(List<String> values) {
            addCriterion("serialID not in", values, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidBetween(String value1, String value2) {
            addCriterion("serialID between", value1, value2, "serialid");
            return (Criteria) this;
        }

        public Criteria andSerialidNotBetween(String value1, String value2) {
            addCriterion("serialID not between", value1, value2, "serialid");
            return (Criteria) this;
        }

        public Criteria andBaudrateIsNull() {
            addCriterion("baudRate is null");
            return (Criteria) this;
        }

        public Criteria andBaudrateIsNotNull() {
            addCriterion("baudRate is not null");
            return (Criteria) this;
        }

        public Criteria andBaudrateEqualTo(Long value) {
            addCriterion("baudRate =", value, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateNotEqualTo(Long value) {
            addCriterion("baudRate <>", value, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateGreaterThan(Long value) {
            addCriterion("baudRate >", value, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateGreaterThanOrEqualTo(Long value) {
            addCriterion("baudRate >=", value, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateLessThan(Long value) {
            addCriterion("baudRate <", value, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateLessThanOrEqualTo(Long value) {
            addCriterion("baudRate <=", value, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateIn(List<Long> values) {
            addCriterion("baudRate in", values, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateNotIn(List<Long> values) {
            addCriterion("baudRate not in", values, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateBetween(Long value1, Long value2) {
            addCriterion("baudRate between", value1, value2, "baudrate");
            return (Criteria) this;
        }

        public Criteria andBaudrateNotBetween(Long value1, Long value2) {
            addCriterion("baudRate not between", value1, value2, "baudrate");
            return (Criteria) this;
        }

        public Criteria andDatabitIsNull() {
            addCriterion("dataBit is null");
            return (Criteria) this;
        }

        public Criteria andDatabitIsNotNull() {
            addCriterion("dataBit is not null");
            return (Criteria) this;
        }

        public Criteria andDatabitEqualTo(Long value) {
            addCriterion("dataBit =", value, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitNotEqualTo(Long value) {
            addCriterion("dataBit <>", value, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitGreaterThan(Long value) {
            addCriterion("dataBit >", value, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitGreaterThanOrEqualTo(Long value) {
            addCriterion("dataBit >=", value, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitLessThan(Long value) {
            addCriterion("dataBit <", value, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitLessThanOrEqualTo(Long value) {
            addCriterion("dataBit <=", value, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitIn(List<Long> values) {
            addCriterion("dataBit in", values, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitNotIn(List<Long> values) {
            addCriterion("dataBit not in", values, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitBetween(Long value1, Long value2) {
            addCriterion("dataBit between", value1, value2, "databit");
            return (Criteria) this;
        }

        public Criteria andDatabitNotBetween(Long value1, Long value2) {
            addCriterion("dataBit not between", value1, value2, "databit");
            return (Criteria) this;
        }

        public Criteria andStopbitIsNull() {
            addCriterion("stopBit is null");
            return (Criteria) this;
        }

        public Criteria andStopbitIsNotNull() {
            addCriterion("stopBit is not null");
            return (Criteria) this;
        }

        public Criteria andStopbitEqualTo(Long value) {
            addCriterion("stopBit =", value, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitNotEqualTo(Long value) {
            addCriterion("stopBit <>", value, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitGreaterThan(Long value) {
            addCriterion("stopBit >", value, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitGreaterThanOrEqualTo(Long value) {
            addCriterion("stopBit >=", value, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitLessThan(Long value) {
            addCriterion("stopBit <", value, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitLessThanOrEqualTo(Long value) {
            addCriterion("stopBit <=", value, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitIn(List<Long> values) {
            addCriterion("stopBit in", values, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitNotIn(List<Long> values) {
            addCriterion("stopBit not in", values, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitBetween(Long value1, Long value2) {
            addCriterion("stopBit between", value1, value2, "stopbit");
            return (Criteria) this;
        }

        public Criteria andStopbitNotBetween(Long value1, Long value2) {
            addCriterion("stopBit not between", value1, value2, "stopbit");
            return (Criteria) this;
        }

        public Criteria andParityIsNull() {
            addCriterion("parity is null");
            return (Criteria) this;
        }

        public Criteria andParityIsNotNull() {
            addCriterion("parity is not null");
            return (Criteria) this;
        }

        public Criteria andParityEqualTo(String value) {
            addCriterion("parity =", value, "parity");
            return (Criteria) this;
        }

        public Criteria andParityNotEqualTo(String value) {
            addCriterion("parity <>", value, "parity");
            return (Criteria) this;
        }

        public Criteria andParityGreaterThan(String value) {
            addCriterion("parity >", value, "parity");
            return (Criteria) this;
        }

        public Criteria andParityGreaterThanOrEqualTo(String value) {
            addCriterion("parity >=", value, "parity");
            return (Criteria) this;
        }

        public Criteria andParityLessThan(String value) {
            addCriterion("parity <", value, "parity");
            return (Criteria) this;
        }

        public Criteria andParityLessThanOrEqualTo(String value) {
            addCriterion("parity <=", value, "parity");
            return (Criteria) this;
        }

        public Criteria andParityLike(String value) {
            addCriterion("parity like", value, "parity");
            return (Criteria) this;
        }

        public Criteria andParityNotLike(String value) {
            addCriterion("parity not like", value, "parity");
            return (Criteria) this;
        }

        public Criteria andParityIn(List<String> values) {
            addCriterion("parity in", values, "parity");
            return (Criteria) this;
        }

        public Criteria andParityNotIn(List<String> values) {
            addCriterion("parity not in", values, "parity");
            return (Criteria) this;
        }

        public Criteria andParityBetween(String value1, String value2) {
            addCriterion("parity between", value1, value2, "parity");
            return (Criteria) this;
        }

        public Criteria andParityNotBetween(String value1, String value2) {
            addCriterion("parity not between", value1, value2, "parity");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(String value) {
            addCriterion("port =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(String value) {
            addCriterion("port <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(String value) {
            addCriterion("port >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(String value) {
            addCriterion("port >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(String value) {
            addCriterion("port <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(String value) {
            addCriterion("port <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLike(String value) {
            addCriterion("port like", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotLike(String value) {
            addCriterion("port not like", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<String> values) {
            addCriterion("port in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<String> values) {
            addCriterion("port not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(String value1, String value2) {
            addCriterion("port between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(String value1, String value2) {
            addCriterion("port not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andDevaddrIsNull() {
            addCriterion("devAddr is null");
            return (Criteria) this;
        }

        public Criteria andDevaddrIsNotNull() {
            addCriterion("devAddr is not null");
            return (Criteria) this;
        }

        public Criteria andDevaddrEqualTo(String value) {
            addCriterion("devAddr =", value, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrNotEqualTo(String value) {
            addCriterion("devAddr <>", value, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrGreaterThan(String value) {
            addCriterion("devAddr >", value, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrGreaterThanOrEqualTo(String value) {
            addCriterion("devAddr >=", value, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrLessThan(String value) {
            addCriterion("devAddr <", value, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrLessThanOrEqualTo(String value) {
            addCriterion("devAddr <=", value, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrLike(String value) {
            addCriterion("devAddr like", value, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrNotLike(String value) {
            addCriterion("devAddr not like", value, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrIn(List<String> values) {
            addCriterion("devAddr in", values, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrNotIn(List<String> values) {
            addCriterion("devAddr not in", values, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrBetween(String value1, String value2) {
            addCriterion("devAddr between", value1, value2, "devaddr");
            return (Criteria) this;
        }

        public Criteria andDevaddrNotBetween(String value1, String value2) {
            addCriterion("devAddr not between", value1, value2, "devaddr");
            return (Criteria) this;
        }

        public Criteria andStationdIdIsNull() {
            addCriterion("stationd_id is null");
            return (Criteria) this;
        }

        public Criteria andStationdIdIsNotNull() {
            addCriterion("stationd_id is not null");
            return (Criteria) this;
        }

        public Criteria andStationdIdEqualTo(String value) {
            addCriterion("stationd_id =", value, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdNotEqualTo(String value) {
            addCriterion("stationd_id <>", value, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdGreaterThan(String value) {
            addCriterion("stationd_id >", value, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdGreaterThanOrEqualTo(String value) {
            addCriterion("stationd_id >=", value, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdLessThan(String value) {
            addCriterion("stationd_id <", value, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdLessThanOrEqualTo(String value) {
            addCriterion("stationd_id <=", value, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdLike(String value) {
            addCriterion("stationd_id like", value, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdNotLike(String value) {
            addCriterion("stationd_id not like", value, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdIn(List<String> values) {
            addCriterion("stationd_id in", values, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdNotIn(List<String> values) {
            addCriterion("stationd_id not in", values, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdBetween(String value1, String value2) {
            addCriterion("stationd_id between", value1, value2, "stationdId");
            return (Criteria) this;
        }

        public Criteria andStationdIdNotBetween(String value1, String value2) {
            addCriterion("stationd_id not between", value1, value2, "stationdId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdIsNull() {
            addCriterion("orgstation_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdIsNotNull() {
            addCriterion("orgstation_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdEqualTo(Long value) {
            addCriterion("orgstation_id =", value, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdNotEqualTo(Long value) {
            addCriterion("orgstation_id <>", value, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdGreaterThan(Long value) {
            addCriterion("orgstation_id >", value, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("orgstation_id >=", value, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdLessThan(Long value) {
            addCriterion("orgstation_id <", value, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdLessThanOrEqualTo(Long value) {
            addCriterion("orgstation_id <=", value, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdIn(List<Long> values) {
            addCriterion("orgstation_id in", values, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdNotIn(List<Long> values) {
            addCriterion("orgstation_id not in", values, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdBetween(Long value1, Long value2) {
            addCriterion("orgstation_id between", value1, value2, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andOrgstationIdNotBetween(Long value1, Long value2) {
            addCriterion("orgstation_id not between", value1, value2, "orgstationId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdIsNull() {
            addCriterion("gateway_id is null");
            return (Criteria) this;
        }

        public Criteria andGatewayIdIsNotNull() {
            addCriterion("gateway_id is not null");
            return (Criteria) this;
        }

        public Criteria andGatewayIdEqualTo(Long value) {
            addCriterion("gateway_id =", value, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdNotEqualTo(Long value) {
            addCriterion("gateway_id <>", value, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdGreaterThan(Long value) {
            addCriterion("gateway_id >", value, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdGreaterThanOrEqualTo(Long value) {
            addCriterion("gateway_id >=", value, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdLessThan(Long value) {
            addCriterion("gateway_id <", value, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdLessThanOrEqualTo(Long value) {
            addCriterion("gateway_id <=", value, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdIn(List<Long> values) {
            addCriterion("gateway_id in", values, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdNotIn(List<Long> values) {
            addCriterion("gateway_id not in", values, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdBetween(Long value1, Long value2) {
            addCriterion("gateway_id between", value1, value2, "gatewayId");
            return (Criteria) this;
        }

        public Criteria andGatewayIdNotBetween(Long value1, Long value2) {
            addCriterion("gateway_id not between", value1, value2, "gatewayId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dms_device
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dms_device
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}