package com.bootdo.devicetree.domain;

import java.io.Serializable;
import java.util.Date;

public class GatewayModelDo implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.type_id
     *
     * @mbg.generated
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.equip_vender
     *
     * @mbg.generated
     */
    private String equipVender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.dms_point_group_id
     *
     * @mbg.generated
     */
    private Long dmsPointGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.dms_protocol_point_group_id
     *
     * @mbg.generated
     */
    private Long dmsProtocolPointGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway_model.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.id
     *
     * @return the value of dms_gateway_model.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.id
     *
     * @param id the value for dms_gateway_model.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.name
     *
     * @return the value of dms_gateway_model.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.name
     *
     * @param name the value for dms_gateway_model.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.type_id
     *
     * @return the value of dms_gateway_model.type_id
     *
     * @mbg.generated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.type_id
     *
     * @param typeId the value for dms_gateway_model.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.equip_vender
     *
     * @return the value of dms_gateway_model.equip_vender
     *
     * @mbg.generated
     */
    public String getEquipVender() {
        return equipVender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.equip_vender
     *
     * @param equipVender the value for dms_gateway_model.equip_vender
     *
     * @mbg.generated
     */
    public void setEquipVender(String equipVender) {
        this.equipVender = equipVender == null ? null : equipVender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.dms_point_group_id
     *
     * @return the value of dms_gateway_model.dms_point_group_id
     *
     * @mbg.generated
     */
    public Long getDmsPointGroupId() {
        return dmsPointGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.dms_point_group_id
     *
     * @param dmsPointGroupId the value for dms_gateway_model.dms_point_group_id
     *
     * @mbg.generated
     */
    public void setDmsPointGroupId(Long dmsPointGroupId) {
        this.dmsPointGroupId = dmsPointGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.dms_protocol_point_group_id
     *
     * @return the value of dms_gateway_model.dms_protocol_point_group_id
     *
     * @mbg.generated
     */
    public Long getDmsProtocolPointGroupId() {
        return dmsProtocolPointGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.dms_protocol_point_group_id
     *
     * @param dmsProtocolPointGroupId the value for dms_gateway_model.dms_protocol_point_group_id
     *
     * @mbg.generated
     */
    public void setDmsProtocolPointGroupId(Long dmsProtocolPointGroupId) {
        this.dmsProtocolPointGroupId = dmsProtocolPointGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.gmt_create
     *
     * @return the value of dms_gateway_model.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.gmt_create
     *
     * @param gmtCreate the value for dms_gateway_model.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.gmt_modified
     *
     * @return the value of dms_gateway_model.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.gmt_modified
     *
     * @param gmtModified the value for dms_gateway_model.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.creator
     *
     * @return the value of dms_gateway_model.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.creator
     *
     * @param creator the value for dms_gateway_model.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.modifier
     *
     * @return the value of dms_gateway_model.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.modifier
     *
     * @param modifier the value for dms_gateway_model.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.remark
     *
     * @return the value of dms_gateway_model.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.remark
     *
     * @param remark the value for dms_gateway_model.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway_model.tenant_id
     *
     * @return the value of dms_gateway_model.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway_model.tenant_id
     *
     * @param tenantId the value for dms_gateway_model.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }
}