package com.bootdo.devicetree.domain;

import java.io.Serializable;
import java.util.Date;

public class GatewayDo implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.gateway_model_id
     *
     * @mbg.generated
     */
    private Long gatewayModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.serial_num
     *
     * @mbg.generated
     */
    private String serialNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.sys_org_id
     *
     * @mbg.generated
     */
    private Long sysOrgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.token
     *
     * @mbg.generated
     */
    private Long token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_gateway.Orgstation_id
     *
     * @mbg.generated
     */
    private Long orgstationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.id
     *
     * @return the value of dms_gateway.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.id
     *
     * @param id the value for dms_gateway.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.gateway_model_id
     *
     * @return the value of dms_gateway.gateway_model_id
     *
     * @mbg.generated
     */
    public Long getGatewayModelId() {
        return gatewayModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.gateway_model_id
     *
     * @param gatewayModelId the value for dms_gateway.gateway_model_id
     *
     * @mbg.generated
     */
    public void setGatewayModelId(Long gatewayModelId) {
        this.gatewayModelId = gatewayModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.address
     *
     * @return the value of dms_gateway.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.address
     *
     * @param address the value for dms_gateway.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.creator
     *
     * @return the value of dms_gateway.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.creator
     *
     * @param creator the value for dms_gateway.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.domain
     *
     * @return the value of dms_gateway.domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.domain
     *
     * @param domain the value for dms_gateway.domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.gmt_create
     *
     * @return the value of dms_gateway.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.gmt_create
     *
     * @param gmtCreate the value for dms_gateway.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.gmt_modified
     *
     * @return the value of dms_gateway.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.gmt_modified
     *
     * @param gmtModified the value for dms_gateway.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.modifier
     *
     * @return the value of dms_gateway.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.modifier
     *
     * @param modifier the value for dms_gateway.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.name
     *
     * @return the value of dms_gateway.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.name
     *
     * @param name the value for dms_gateway.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.remark
     *
     * @return the value of dms_gateway.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.remark
     *
     * @param remark the value for dms_gateway.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.serial_num
     *
     * @return the value of dms_gateway.serial_num
     *
     * @mbg.generated
     */
    public String getSerialNum() {
        return serialNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.serial_num
     *
     * @param serialNum the value for dms_gateway.serial_num
     *
     * @mbg.generated
     */
    public void setSerialNum(String serialNum) {
        this.serialNum = serialNum == null ? null : serialNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.sys_org_id
     *
     * @return the value of dms_gateway.sys_org_id
     *
     * @mbg.generated
     */
    public Long getSysOrgId() {
        return sysOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.sys_org_id
     *
     * @param sysOrgId the value for dms_gateway.sys_org_id
     *
     * @mbg.generated
     */
    public void setSysOrgId(Long sysOrgId) {
        this.sysOrgId = sysOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.token
     *
     * @return the value of dms_gateway.token
     *
     * @mbg.generated
     */
    public Long getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.token
     *
     * @param token the value for dms_gateway.token
     *
     * @mbg.generated
     */
    public void setToken(Long token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.type
     *
     * @return the value of dms_gateway.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.type
     *
     * @param type the value for dms_gateway.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_gateway.Orgstation_id
     *
     * @return the value of dms_gateway.Orgstation_id
     *
     * @mbg.generated
     */
    public Long getOrgstationId() {
        return orgstationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_gateway.Orgstation_id
     *
     * @param orgstationId the value for dms_gateway.Orgstation_id
     *
     * @mbg.generated
     */
    public void setOrgstationId(Long orgstationId) {
        this.orgstationId = orgstationId;
    }
}